import React from 'react'

const AboutUs = () => {
    return (
        <div>
            <div className='flex justify-center items-center py-5'>
                <p className='text-4xl text-black font-bold shadow p-5'>About us</p>
            </div>
            <div>
                <div className=''>
                    <p>The mid nineties and the subsequent decade saw much international debate &amp; discussion around Disaster Response &amp; Preparedness. Some of the notable and more impactful ones were the Yokohama Strategy Plan (1994) &amp; the Hyogo Framework for Action (2005), adopted by the UN. During the same period India faced some of its most severe natural calamities like Orissa Super Cyclone (1999), Gujarat Earthquake (2001) and Indian Ocean Tsunami (2004). This succession of events and the International environment brought to fore, the need of comprehensive disaster management plan. This led to the enactment of the Disaster Management Act on December 26th , 2005. The National Disaster Management Authority (NDMA) was constituted to lay down the policies, plans and guidelines for disaster management.</p>
                    <p>The Disaster Management Act has statutory provisions for constitution of National Disaster Response Force (NDRF) for the purpose of specialized response to natural and man-made disasters. Accordingly, in 2006 NDRF was constituted with 8 Battalions. At present, NDRF has a strength of 12 Battalions with each Battalion consisting of 1149 personnel. In the beginning, the personnel of NDRF were deployed for routine law and order duties also. In a meeting of the NDMA with the Prime Minister on October 25, 2007, the need of NDRF being made a dedicated force was highlighted and accepted. This led to the notification of NDRF Rules on February 14th , 2008, making NDRF a dedicated force for disaster response related duties, under the unified command of DG NDRF.</p>
                    <p>The practice of “proactive availability” of this Force to the States and that of “pre-positioning”, in a threatening disaster situations have immensely helped minimise damage, caused due to natural calamities in the country. The first major test of disaster for NDRF was Kosi Floods in 2008. NDRF resources were moved to Bihar immediately after the breach in Kosi barrage on 19th August 2008. The situation was handled by the NDRF on a war footing, by airlifting 153 high speed motorized boats with 780 flood rescue trained personnel drawn from three different Battalions and sent to the five flood affected districts with utmost promptitude. As a result, over 1,00,000 affected people were rescued during the initial stage itself. The prompt and timely response of NDRF was appreciated by the then Chief Minister of Bihar.</p>
                    <p>Since its inception NDRF has continued to win hearts of millions of countrymen, by demonstrating its expertise and compassion while handling disaster situations. The list of such challenges is long. To cite a few ; a six storey building collapsed at Bellary (Karnataka) in January 2010. In a meticulously planned, round the clock operation lasting seven days, the NDRF rescued 20 trapped live victims and retrieved 29 bodies. In a multi-storey factory building collapse at Jalandhar (Punjab) in April 2012, the NDRF successfully rescued 12 live victims trapped under huge rubble of debris and also recovered 19 dead bodies. The sterling services rendered by 46 NDRF personnel in response to the triple disaster in Japan in March-April 2011, has also won NDRF laurels.</p>
                    <p>In September 2014, the Jammu and Kashmir region suffered disastrous floods across many of its districts caused by torrential rainfall. This was the first-ever experience for NDRF to handle urban flooding on such a massive scale. At the time that the NDRF teams arrived in Srinagar in response to the sudden floods, there was huge expanse of water, clusters of half-submerged houses, broken bridges, roads which were washed away &amp; lakhs of people stranded on rooftops. Adding to the woes were non functional communication &amp; electricity supply. NDRF, with an initial strength of 10 teams and 50 inflatable rubberized boats, was engaged relentlessly in evacuating stranded people and saving lives. Subsequently, the strength of teams was raised to 23 with more than 150 boats, which rescued more than 50,000 people and distributed nearly 80 tones of relief material.</p>
                    <p>When cyclone Hud-hud pounded the eastern Indian coast in October 2014, NDRF personnel were present there to save lives of the affected people. They used saw cutters to cut big trees and other metal objects likely to be uprooted and scattered by the gusty and ferocious winds of Hud-hud.</p>
                    <p>When on 25 April 2015, an earthquake with a magnitude of 7.8 and a depth of 15 km struck Nepal, India’s National Disaster Response Force made the headlines by capitalizing the golden hours’ rule of disaster management by being the first on the ground. In the rescue operations, the personnel of NDRF pulled out 11 live victims out of a total figure of 16.</p>
                    <p>In later part of 2015, NDRF created a milestone in one of the marathon rescue operations of its kind in Bilaspur tunnel accident in Himachal Pradesh when two workers were trapped for nine days. Two workers were safely retrieved from a collapsed under-construction tunnel. In month of Dec 2015 unprecedented rain has flooded parts of Tamilnadu and Puducherry which resulted in urban flood in Chennai and its suburbs. NDRF mobilised 50 USAR teams from different location across the country by Air and timely evacuated more than 14,000 flood affected people and shifted them to safer areas. NDRF teams also assisted local administration by providing immediate relief and medical care to thousands of needy people. Role of NDRF during Chennai was appreciated by all corners of society,</p>
                    <p>Besides the professionalism shown during rescue operations in floods and cyclones and collapsed structure search and rescue (CSSR) operations, NDRF has also acquired considerable expertise in facing CBRN (Chemical, Biological, Radiological &amp; Nuclear) challenges. . The creditable task of NDRF in retrieving Cobalt-60 radiological material at Mayapuri, Delhi, during April and May 2010 has been an acid test of NDRF's CBRN capability.</p>
                    <p>Today NDRF is a distinguished, unique Force across the country functioning under the Ministry of Home Affairs, Government of India, within the overall command, control and leadership of the Director General, NDRF.</p>
                    <p><strong>ORGANISATION</strong></p>
                    <p>At present, National Disaster Response Force consist of 15 battalions from the BSF, CISF, CRPF, ITBP, SSB and Assam Rifles. Each battalion have 18 self-contained specialist search and rescue teams of 45 personnel each including engineers, technicians, electricians, dog squads and medical/paramedics. The total strength of each battalion is 1,149. All the 15 battalions have been equipped and trained to respond natural as well as man-made disasters. Battalions are also trained and equipped for response during chemical, biological, radiological and nuclear (CBRN) emergencies.</p>
                    <p><strong>LOCATIONS OF NDRF BNs</strong><br />These NDRF battalions are located at 16 different locations in the country based on the vulnerability profile of country and to cut down the response time for their deployment at disaster site.</p>
                    <p ></p>
                    <p ><img src="sites/default/files/ndrflocationmap.png"  /></p>
                    <p  ><span color="#434746"><span face="Times New Roman, serif"><span size="3">Map showing NDRF Bns locations and their respective area of responsibility</span></span></span></p>
                </div>
            </div>
        </div>
    )
}

export default AboutUs